[2m2025-07-02T01:50:11.975674Z[0m [[32m[1minfo     [0m] [1mEnvironment 'dev' is active   [0m
[2m2025-07-02T01:50:12.192611Z[0m [[32m[1minfo     [0m] [1mMarked stale run that started at 2025-07-02 01:42:35.325414+00:00 as failed: No heartbeat recorded for 5 minutes. The process was likely killed unceremoniously.[0m
[2m2025-07-02T01:50:12.193035Z[0m [[33m[1mwarning  [0m] [1mForce option is enabled, ignoring stale job check.[0m
[2m2025-07-02T01:50:12.349938Z[0m [[32m[1minfo     [0m] [1mUsing systemdb state backend  [0m
[2m2025-07-02T01:50:12.351447Z[0m [[33m[1mwarning  [0m] [1mNo state was found, complete import.[0m
[2m2025-07-02T01:50:15.895252Z[0m [[32m[1minfo     [0m] [1müéµ Starting Singer message processing[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.895694Z[0m [[32m[1minfo     [0m] [1müîå Connecting to Oracle: 10.93.10.114:1522/gbe8f3f2dbbc562_dwpdb_low.adb.oraclecloud.com[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.895951Z[0m [[32m[1minfo     [0m] [1müîê Protocol: tcps, User: oic   [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.896181Z[0m [[32m[1minfo     [0m] [1m‚ùå Oracle connection failed: connect() got an unexpected keyword argument 'timeout'[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.896459Z[0m [[32m[1minfo     [0m] [1mTraceback (most recent call last):[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.896586Z[0m [[32m[1minfo     [0m] [1m  File "/home/marlonsc/flext/gruponos-meltano-native/simple_target_oracle_fixed.py", line 44, in get_oracle_connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.896681Z[0m [[32m[1minfo     [0m] [1m    connection = oracledb.connect([0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.896766Z[0m [[32m[1minfo     [0m] [1m        user=username,        [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.896851Z[0m [[32m[1minfo     [0m] [1m    ...<2 lines>...           [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.896935Z[0m [[32m[1minfo     [0m] [1m        timeout=60            [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.897017Z[0m [[32m[1minfo     [0m] [1m    )                         [0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.897102Z[0m [[32m[1minfo     [0m] [1m  File "/home/marlonsc/flext/.venv/lib/python3.13/site-packages/oracledb/connection.py", line 1186, in connect[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.897186Z[0m [[32m[1minfo     [0m] [1m    f(dsn=dsn, pool=pool, conn_class=conn_class, params=params, **kwargs)[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.897275Z[0m [[32m[1minfo     [0m] [1m    ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.897367Z[0m [[32m[1minfo     [0m] [1mTypeError: connect() got an unexpected keyword argument 'timeout'[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.897458Z[0m [[32m[1minfo     [0m] [1m‚ùå Failed to get Oracle connection[0m [36mcmd_type[0m=[35melb[0m [36mconsumer[0m=[35mTrue[0m [36mjob_name[0m=[35mdev:tap-oracle-wms-to-target-oracle[0m [36mname[0m=[35mtarget-oracle[0m [36mproducer[0m=[35mFalse[0m [36mrun_id[0m=[35md7d00bf4-e2bc-43fd-8855-0e5278c2f193[0m [36mstdio[0m=[35mstderr[0m [36mstring_id[0m=[35mtarget-oracle[0m
[2m2025-07-02T01:50:15.941812Z[0m [[31m[1merror    [0m] [1mLoader failed                 [0m
[2m2025-07-02T01:50:15.942026Z[0m [[31m[1merror    [0m] [1mBlock run completed.          [0m [36mblock_type[0m=[35mExtractLoadBlocks[0m [36merr[0m=[35mRunnerError('Loader failed')[0m [36mexit_codes[0m=[35m{<PluginType.LOADERS: 'loaders'>: 1}[0m [36mset_number[0m=[35m0[0m [36msuccess[0m=[35mFalse[0m
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Loader failed
